FROM openjdk:17
COPY illchess-player-info-server/target/illchess-player-info-server-1.0.0-SNAPSHOT-runner.jar illchess-player-info-server-1.0.0-SNAPSHOT-runner.jar
ENTRYPOINT ["java", "-jar", "illchess-player-info-server-1.0.0-SNAPSHOT-runner.jar"]
EXPOSE 420