name: illchess
services:
  gamedb:
    container_name: game-db
    image: redis:7.0.11-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  chess-web-socket-service:
    container_name: illchess-web-socket-service
    image: illchess-web-socket-service
    ports:
      - 8080:8080
    depends_on:
      gamedb:
        condition: service_healthy
    environment:
      - REDIS_HOSTNAME=6379
      - REDIS_HOSTNAME=gamedb
  chess-stockfish-service:
    container_name: illchess-stockfish-service
    image: illchess-stockfish-service
    ports:
      - 2137:2137
    environment:
      - URLS_GAME-SERVICE=http://illchess-web-socket-service:8080