FROM openjdk:17
COPY illchess-game-server/target/illchess-game-server-0.0.1-SNAPSHOT.jar illchess-game-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "illchess-game-server-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080