quarkus:
  http:
    port: 420
  package:
    jar:
      type: uber-jar
  datasource:
    jdbc:
      driver: com.mysql.cj.jdbc.Driver
      url: "jdbc:mysql://localhost:3306/player_info_db"
    username: admin
    password: admin
  liquibase:
    migrate-at-start: true
    change-log: classpath:db/db.changelog-master.yaml
mp:
  messaging:
    incoming:
      obtain-game:
        connector: smallrye-rabbitmq
        queue:
          name: obtain-game
        exchange:
          name: obtain-game
    outgoing:
      obtain-game-success:
        connector: smallrye-rabbitmq
        exchange:
          name: obtain-game-success
      obtain-game-failure:
        connector: smallrye-rabbitmq
        exchange:
          name: obtain-game-failure

rabbitmq-host: localhost
rabbitmq-port: 5672
rabbitmq-username: guest
rabbitmq-password: guest