quarkus:
  http:
    port: 420
  package:
    jar:
      type: uber-jar
mp:
  messaging:
    incoming:
      obtain-game:
        connector: smallrye-rabbitmq
        queue:
          name: obtain-game
        exchange:
          name: obtain-game

rabbitmq-host: localhost
rabbitmq-port: 5672
rabbitmq-username: guest
rabbitmq-password: guest