quarkus:
  http:
    port: 2137
  package:
    jar:
      type: uber-jar
urls:
  game-service: "http://localhost:8080"
  stockfish-api: "https://stockfish.online/api/s/v2.php"
# POSSIBLE VALUES: ENGINE, API
working:
  mode: ENGINE
