server:
  port: 1337

spring:
  cloud:
    gateway:
      default-filters:
        - StripPrefix=2
      routes:
        - id: illchess-web-socket-service
          uri: http://localhost:8080
          predicates:
            - Path=/gateway/game/**
        - id: illchess-stockfish-service
          uri: http://localhost:2137
          predicates:
            - Path=/gateway/stockfish/**
        - id: illchess-player-info-service
          uri: http://localhost:420
          predicates:
            - Path=/gateway/player-info/**